const {app,BrowserWindow,ipcMain,dialog}=require('electron');
const path=require('path');const fs=require('fs');const os=require('os');const {execFile}=require('child_process');
const isDev=!app.isPackaged;let mainWindow;
function createWindow(){mainWindow=new BrowserWindow({width:1440,height:900,minWidth:1100,minHeight:700,backgroundColor:'#020617',show:false,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});mainWindow.once('ready-to-show',()=>mainWindow.show());if(isDev)mainWindow.loadURL('http://localhost:3000');else mainWindow.loadFile(path.join(__dirname,'../dist/index.html'));mainWindow.on('closed',()=>{mainWindow=null});}
app.whenReady().then(()=>{registerIpc();createWindow();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()})});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
function registerIpc(){
 ipcMain.handle('system:info',()=>({platform:process.platform,arch:process.arch,hostname:os.hostname(),user:os.userInfo().username,appVersion:app.getVersion()}));
 ipcMain.handle('files:choose',async()=>{const r=await dialog.showOpenDialog(mainWindow,{properties:['openFile','multiSelections'],filters:[{name:'Documents',extensions:['pdf','doc','docx','ppt','pptx','xls','xlsx','jpg','jpeg','png']},{name:'All files',extensions:['*']}]});return r.canceled?[]:r.filePaths;});
 ipcMain.handle('files:stat',(_,filePath)=>{if(typeof filePath!=='string')throw new Error('Invalid file path');const s=fs.statSync(filePath);return {path:filePath,name:path.basename(filePath),size:s.size,modifiedAt:s.mtime.toISOString(),isFile:s.isFile()};});
 ipcMain.handle('printers:list',()=>new Promise((resolve,reject)=>{if(process.platform!=='win32'){resolve([]);return}const command="Get-Printer | Select-Object Name,PrinterStatus,DriverName,PortName,WorkOffline | ConvertTo-Json -Compress";execFile('powershell.exe',['-NoProfile','-NonInteractive','-Command',command],{windowsHide:true},(err,stdout)=>{if(err){reject(new Error('Windows printer discovery failed: '+err.message));return}try{if(!stdout.trim()){resolve([]);return}const data=JSON.parse(stdout);const rows=Array.isArray(data)?data:[data];resolve(rows.map(x=>({name:x.Name,status:x.PrinterStatus,driver:x.DriverName,port:x.PortName,offline:Boolean(x.WorkOffline)})));}catch{reject(new Error('Could not parse Windows printer information.'));}})}));
 ipcMain.handle('printer:open',(_,printerName)=>{if(process.platform!=='win32')throw new Error('Printer actions are currently supported on Windows only.');return new Promise((resolve,reject)=>execFile('rundll32.exe',['printui.dll,PrintUIEntry','/o','/n',printerName],{windowsHide:true},err=>err?reject(new Error('Could not open printer queue.')):resolve(true))});
}